### ISSUE TITLE
plugin crashes when executed during a backup

### ISSUE THREAD

**Issue by yennor** [edvler/check_mk_proxmox-qemu-backup#4] opened 2019-08-14 04:35 UTC
The plugin crashes (on the check_mk site) regularly. If I see it right, it crashes while a backups is executed. I'm using check-mk 1.6.0b5 .

I'm not sure if it's the same bug as #1 , but I've tried the changed files from there, and it is exactly the same behaviour.  Here the crash log:

### Exception	
IndexError (list index out of range)

### Traceback
File "/omd/sites/rmm/lib/python/cmk_base/checking.py", line 319, in execute_check
    raw_result = check_function(item, determine_check_params(params), section_content)
  File "/omd/sites/rmm/local/share/check_mk/checks/proxmox_qemu_backup", line 112, in check_qemu_backup
    startdate = getDateFromFileCreated(file_created[offset+6].split("/")[-1])

### Locale variables

{'archive': 'nothing',
 'content': u'05',
 'd': time.struct_time(tm_year=2019, tm_mon=8, tm_mday=14, tm_hour=3, tm_min=17, tm_sec=49, tm_wday=2, tm_yday=226, tm_isdst=-1),
 'error_count': 0,
 'file_created': [u'/var/log/vzdump/qemu-100.log',
                  u'2019-08-14',
                  u'03:17:49',
                  u'INFO:',
                  u'creating',
                  u'archive',
                  u"'/mnt/backup_usb/dump/vzdump-qemu-100-2019_08_14-03_17_47.vma.gz'"],
 'finished': 'nothing',
 'info': [[u'QEMU-MACHINE;;;;;/etc/pve/qemu-server/104.conf;;;;;fischprogramme2'],
          [u'QEMU-MACHINE;;;;;/etc/pve/qemu-server/100.conf;;;;;lasso'],
          [u'QEMU-MACHINE;;;;;/etc/pve/qemu-server/105.conf;;;;;Win7Pro64bit'],
          [u'QEMU-MACHINE;;;;;/etc/pve/qemu-server/103.conf;;;;;lasso-old'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:47',
           u'INFO:',
           u'Starting',
           u'Backup',
           u'of',
           u'VM',
           u'100',
           u'(qemu)'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:47',
           u'INFO:',
           u'status',
           u'=',
           u'running'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:48',
           u'INFO:',
           u'update',
           u'VM',
           u'100:',
           u'-lock',
           u'backup'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:48',
           u'INFO:',
           u'VM',
           u'Name:',
           u'lasso'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:48',
           u'INFO:',
           u'include',
           u'disk',
           u"'virtio0'",
           u"'lvm-vg-pve:vm-100-disk-2'",
           u'250G'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:48',
           u'INFO:',
           u'include',
           u'disk',
           u"'virtio1'",
           u"'lvm-vg-pve:vm-100-disk-1'",
           u'2G'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:49',
           u'INFO:',
           u'backup',
           u'mode:',
           u'snapshot'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:49',
           u'INFO:',
           u'ionice',
           u'priority:',
           u'7'],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:49',
           u'INFO:',
           u'creating',
           u'archive',
           u"'/mnt/backup_usb/dump/vzdump-qemu-100-2019_08_14-03_17_47.vma.gz'"],
          [u'/var/log/vzdump/qemu-100.log',
           u'2019-08-14',
           u'03:17:49',
           u'INFO:',
           u'started',
           u'backup',
           u'task',
           u"'5e435ff3-b78c-4f21-b837-30f6c2b6ee17'"],
          [u'/var/log/vzdump/qemu-100.log', u'2019-08-14', u'05'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:02',
           u'INFO:',
           u'Starting',
           u'Backup',
           u'of',
           u'VM',
           u'103',
           u'(qemu)'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:02',
           u'INFO:',
           u'status',
           u'=',
           u'running'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'update',
           u'VM',
           u'103:',
           u'-lock',
           u'backup'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'VM',
           u'Name:',
           u'lasso2'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'include',
           u'disk',
           u"'virtio0'",
           u"'lvm-vg-pve:vm-103-disk-1'",
           u'200G'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'include',
           u'disk',
           u"'virtio1'",
           u"'lvm-vg-pve:vm-103-disk-2'",
           u'2G'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'backup',
           u'mode:',
           u'snapshot'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'ionice',
           u'priority:',
           u'7'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'creating',
           u'archive',
           u"'/mnt/backup_usb/dump/vzdump-qemu-103-2019_06_14-00_15_02.vma.gz'"],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:15:03',
           u'INFO:',
           u'started',
           u'backup',
           u'task',
           u"'ba7c6dbb-caf2-4cd5-bca5-9a6ec98033d8'"],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:27:09',
           u'ERROR:',
           u'vma_queue_write:',
           u'write',
           u'error',
           u'-',
           u'Broken',
           u'pipe'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:27:09',
           u'INFO:',
           u'aborting',
           u'backup',
           u'job'],
          [u'/var/log/vzdump/qemu-103.log',
           u'2019-06-14',
           u'00:27:11',
           u'ERROR:',
           u'Backup',
           u'of',
           u'VM',
           u'103',
           u'failed',
           u'-',
           u'vma_queue_write:',
           u'write',
           u'error',
           u'-',
           u'Broken',
           u'pipe'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:41',
           u'INFO:',
           u'Starting',
           u'Backup',
           u'of',
           u'VM',
           u'104',
           u'(qemu)'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:41',
           u'INFO:',
           u'status',
           u'=',
           u'running'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'update',
           u'VM',
           u'104:',
           u'-lock',
           u'backup'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'VM',
           u'Name:',
           u'fischprogramme2'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'include',
           u'disk',
           u"'virtio0'",
           u"'lvm-vg-pve:vm-104-disk-2'",
           u'50G'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'include',
           u'disk',
           u"'virtio1'",
           u"'lvm-vg-pve:vm-104-disk-1'",
           u'2G'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'backup',
           u'mode:',
           u'snapshot'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'ionice',
           u'priority:',
           u'7'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'creating',
           u'archive',
           u"'/mnt/backup_usb/dump/vzdump-qemu-104-2019_08_14-02_34_41.vma.gz'"],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'02:34:42',
           u'INFO:',
           u'started',
           u'backup',
           u'task',
           u"'88704680-7481-4107-840b-f2fb9298d331'"],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'03:17:46',
           u'INFO:',
           u'transferred',
           u'55834',
           u'MB',
           u'in',
           u'2584',
           u'seconds',
           u'(21',
           u'MB/s)'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'03:17:46',
           u'INFO:',
           u'archive',
           u'file',
           u'size:',
           u'8.93GB'],
          [u'/var/log/vzdump/qemu-104.log',
           u'2019-08-14',
           u'03:17:47',
           u'INFO:',
           u'Finished',
           u'Backup',
           u'of',
           u'VM',
           u'104',
           u'(00:43:06)']],
 'item': u'lasso Id: 100',
 'line': [u'/var/log/vzdump/qemu-104.log',
          u'2019-08-14',
          u'03:17:47',
          u'INFO:',
          u'Finished',
          u'Backup',
          u'of',
          u'VM',
          u'104',
          u'(00:43:06)'],
 'line_count': 11,
 'logfile': u'/var/log/vzdump/qemu-100.log',
 'offset': 1,
 'params': {'backup_age': (93600, 108000),
            'check_backup': 'check',
            'running_time': 25200},
 'qemu_id': u'100',
 'started': [u'/var/log/vzdump/qemu-100.log',
             u'2019-08-14',
             u'03:17:47',
             u'INFO:',
             u'Starting',
             u'Backup',
             u'of',
             u'VM',
             u'100',
             u'(qemu)'],
 'warn_count': 0}

### Agent output
<<<proxmox_qemu_backup>>>
QEMU-MACHINE;;;;;/etc/pve/qemu-server/104.conf;;;;;fischprogramme2
QEMU-MACHINE;;;;;/etc/pve/qemu-server/100.conf;;;;;lasso
QEMU-MACHINE;;;;;/etc/pve/qemu-server/105.conf;;;;;Win7Pro64bit
QEMU-MACHINE;;;;;/etc/pve/qemu-server/103.conf;;;;;lasso-old
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:47 INFO: Starting Backup of VM 100 (qemu)
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:47 INFO: status = running
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:48 INFO: update VM 100: -lock backup
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:48 INFO: VM Name: lasso
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:48 INFO: include disk 'virtio0' 'lvm-vg-pve:vm-100-disk-2' 250G
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:48 INFO: include disk 'virtio1' 'lvm-vg-pve:vm-100-disk-1' 2G
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:49 INFO: backup mode: snapshot
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:49 INFO: ionice priority: 7
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:49 INFO: creating archive '/mnt/backup_usb/dump/vzdump-qemu-100-2019_08_14-03_17_47.vma.gz'
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:49 INFO: started backup task '5e435ff3-b78c-4f21-b837-30f6c2b6ee17'
/var/log/vzdump/qemu-100.log 2019-08-14 05
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:02 INFO: Starting Backup of VM 103 (qemu)
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:02 INFO: status = running
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: update VM 103: -lock backup
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: VM Name: lasso2
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: include disk 'virtio0' 'lvm-vg-pve:vm-103-disk-1' 200G
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: include disk 'virtio1' 'lvm-vg-pve:vm-103-disk-2' 2G
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: backup mode: snapshot
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: ionice priority: 7
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: creating archive '/mnt/backup_usb/dump/vzdump-qemu-103-2019_06_14-00_15_02.vma.gz'
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: started backup task 'ba7c6dbb-caf2-4cd5-bca5-9a6ec98033d8'
/var/log/vzdump/qemu-103.log 2019-06-14 00:27:09 ERROR: vma_queue_write: write error - Broken pipe
/var/log/vzdump/qemu-103.log 2019-06-14 00:27:09 INFO: aborting backup job
/var/log/vzdump/qemu-103.log 2019-06-14 00:27:11 ERROR: Backup of VM 103 failed - vma_queue_write: write error - Broken pipe
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:41 INFO: Starting Backup of VM 104 (qemu)
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:41 INFO: status = running
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: update VM 104: -lock backup
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: VM Name: fischprogramme2
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: include disk 'virtio0' 'lvm-vg-pve:vm-104-disk-2' 50G
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: include disk 'virtio1' 'lvm-vg-pve:vm-104-disk-1' 2G
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: backup mode: snapshot
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: ionice priority: 7
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: creating archive '/mnt/backup_usb/dump/vzdump-qemu-104-2019_08_14-02_34_41.vma.gz'
/var/log/vzdump/qemu-104.log 2019-08-14 02:34:42 INFO: started backup task '88704680-7481-4107-840b-f2fb9298d331'
/var/log/vzdump/qemu-104.log 2019-08-14 03:17:46 INFO: transferred 55834 MB in 2584 seconds (21 MB/s)
/var/log/vzdump/qemu-104.log 2019-08-14 03:17:46 INFO: archive file size: 8.93GB
/var/log/vzdump/qemu-104.log 2019-08-14 03:17:47 INFO: Finished Backup of VM 104 (00:43:06)

**Comment by edvler** [comment] 2019-08-16 20:18
The reason for the error is a **incomplete line** in the agent output.

### Problem
Look in the agent output at the following lines:
...
/var/log/vzdump/qemu-100.log 2019-08-14 03:17:49 INFO: started backup task '5e435ff3-b78c-4f21-b837-30f6c2b6ee17'
**/var/log/vzdump/qemu-100.log 2019-08-14 05**
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:02 INFO: Starting Backup of VM 103 (qemu)
....
The bold line looks like it was cut after the hour. The rest of the line is missing.

It's confirmend by the array output of the dump. The array only contains the elements from the bold line.
...
[u'/var/log/vzdump/qemu-100.log', u'2019-08-14', u'05'],
...
Because there is no element with number 6, a index error is thrown. No chance to get a valid date from this line.

### Solution
It's no a problem of the check plugin. Maybe the problem is, that the log is not completly written to the disk. When the check plugin reads the logfile it gets a incomplete logline.
It's not a duplicate of bug #1.

Some guesses:
* IO-load to high when backup is running (backup destination and log destination on the same device)?
* Disk full an no more log-output could be written unless disk space is avaliable?
* Maybe a setting of vzdump howto write/cache log-files?

You can also try to execute the plugin in a shell:
/usr/lib/check_mk_agent/plugins/urbackup-check
Can you reproduce the incomplete output?

**Comment by yennor** [comment] 2019-08-24 00:44
ok, I've finally managed to look into it. Sorry it took that long. But the backups are in the middle of the night. And when I've started them by hand the issued didn't seem to arrise (ok, I've never waited longer than 30 minutes, and then stopped the backup).
- IO-load and CPU load are low. (backup source and destionation are on different devices, also the log file is not written to the backup device). Also the plugin crashes for 40-60 minutes and then it works again.
- Disks aren't full
- vzdump doesn't seem to have settings about how to write the log files?

When I executed the plugin directly in a shell. it's the same output.
Actually the end of /var/log/vzdump/qemu-100.log looks like:

`2019-08-24 01:39:13 INFO: status: 54% (146157010944/270582939648), sparse 22% (60913139712), duration 7750, read/write 143/0 MB/s
2019-08-24 01:39:34 INFO: status: 55% (148900282368/270582939648), sparse 23% (63656206336), duration 7771, read/write 130/0 MB/s
2019-08-24 01:39:53 INFO: status: 56% (151543087104/270582939648), sparse 24% (66298941440), duration 7790, read/write 139/0 MB/s
2019-08-24 01:40:12 INFO: status: 57% (154243694592/270582939648), sparse 25% (68999471104), duration 7809, read/write 142/0 MB/s
2019-08-24 01:40:33 INFO: status: 58% (157096738816/270582939648), sparse 26% (71849558016), duration 7830, read/write 135/0 MB/s
2019-08-24 01:40:55 INFO: status: 59% (159775064064/270582939648), sparse 27% (74489667584), duration 7852, read/write 121/1 MB/s
2019-08-24 01:42:47 INFO: status: 60% (162396504064/270582939648), sparse 27% (75655229440), duration 7964, read/write 23/12 MB/s
2019-08-24 01:43:47 INFO: status: 61% (165119262720/270582939648), sparse 28% (77537742848), duration 8024, read/write 45/14 MB/s
2019-08-24 01:44:56 INFO: status: 62% (167791427584/270582939648), sparse 29% (79528849408), duration 8093, read/write 38/9 MB/s
2019-08-24
`
As you can see, there is only a date, and right now it is 2:25. So eventhough the backup continues (I've checked) there is no noticable load on the server at all, and no error message anywhere I've could find. Before 1:44:56 the logs were correctly, because only afterwards I've got a warning-mail from check-mk.
When I log into the gui, the backup process is at:
`
INFO: status: 83% (224598687744/270582939648), sparse 41% (111812489216), duration 10425, read/write 27/9 MB/s
INFO: status: 84% (227305062400/270582939648), sparse 41% (113220243456), duration 10545, read/write 22/10 MB/s`

So it continues, it just stopped logging to the log file for a while.
As soon as the backup finishes, the rest of the log file are written. And everything's back to normal. I would guess there is some kind of write buffer? I'm watching the next backup right now. The logfile is also way behind of what is shown in the gui. But without a half write which makes the plugin crash.
But strange that that doesn't happen on your system?

The proxmox version on the system right now is: 5.2

**Comment by edvler** [comment] 2019-09-12 14:34
Hello,

sorry for my late feedback.
I dont have alerts for my Proxmox-Backup-checks while backups are running. I think my logs are written correctly.

My oldest Proxmox Version is: 5.4-5.
Maybe in newer versions such a problem don't exists?!

Greets

**Comment by edvler** [comment] 2020-01-31 16:45
Hello,

i changed the logic for detecting if a backup is currently running. Now the check is not using the logfiles content while the vzdump process is running.

If you want to give it a try you have to replace all files on your Check_MK server under /opt/omd/sites/-YOURSITE-/local/share/check_mk with the new ones from https://github.com/edvler/check_mk_proxmox-qemu-backup/tree/master/check_mk.

Please give a feedback. If it's working i'll release an new .mkp file.

Greets

**Comment by yennor** [comment] 2020-02-04 15:58
hi

meanwhile we've updated the proxmox version. And also there was heavy load on the server while the backup was running. We've also managed to reduce the load. And the problem doesn't happen anymore with the old version. But since we had the plugin deactivated, I'm not sure which was the reason. The proxmox version or the load. so or so. I can't check if there is any difference from the old to the new version.
But I've just installed the new version. And it also works.
Sorry I can't say anything more. But thanks for your effort. And I guess since not the logfile content is checked anymore it should solve the problem.

**Comment by yennor** [comment] 2020-02-05 02:51
ups. I was wrong.
It didn't work tonight. Here the output from /usr/lib/check_mk_agent/plugins/proxmox_qemu_backup . it still seems to be cut off

> <<<proxmox_qemu_backup>>>
QEMU-MACHINE;;;;;/etc/pve/qemu-server/104.conf;;;;;fischprogramme2
QEMU-MACHINE;;;;;/etc/pve/qemu-server/100.conf;;;;;lasso
QEMU-MACHINE;;;;;/etc/pve/qemu-server/105.conf;;;;;Win7Pro64bit
QEMU-MACHINE;;;;;/etc/pve/qemu-server/101.conf;;;;;lasso-old-stretch
PSOUTPUT root     18795  0.0  0.0   4280   748 ?        Ss   Feb04   0:00 /bin/sh -c vzdump 104 100 105 --mode snapshot --quiet 1 --compress gzip --storage usb_daily_2weeks
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:02 INFO: Starting Backup of VM 100 (qemu)
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:02 INFO: status = running
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: update VM 100: -lock backup
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: VM Name: lasso
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: include disk 'virtio0' 'lvm-vg-pve:vm-100-disk-2' 250G
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: include disk 'virtio1' 'lvm-vg-pve:vm-100-disk-1' 2G
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: backup mode: snapshot
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: ionice priority: 7
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: pending configuration changes found (not included into backup)
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:03 INFO: creating archive '/mnt/backup_usb/dump/vzdump-qemu-100-2020_02_04-22_30_02.vma.gz'
/var/log/vzdump/qemu-100.log 2020-02-04 22:30:04 INFO: started backup task '15aa070d-3bad-491f-976f-7e58736a9d83'
/var/log/vzdump/qemu-100.log 2020-02-05 03:09:16 INFO: transferred 270582 MB in 16752 seconds (16 MB/s)
/var/log/vzdump/qemu-100.log 2020-02-05 03:09:16 INFO: archive file size: 132.05GB
/var/log/vzdump/qemu-100.log 2020-02-05 03:09:17 INFO: Finished Backup of VM 100 (04:39:15)
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:02 INFO: Starting Backup of VM 103 (qemu)
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:02 INFO: status = running
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: update VM 103: -lock backup
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: VM Name: lasso2
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: include disk 'virtio0' 'lvm-vg-pve:vm-103-disk-1' 200G
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: include disk 'virtio1' 'lvm-vg-pve:vm-103-disk-2' 2G
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: backup mode: snapshot
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: ionice priority: 7
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: creating archive '/mnt/backup_usb/dump/vzdump-qemu-103-2019_06_14-00_15_02.vma.gz'
/var/log/vzdump/qemu-103.log 2019-06-14 00:15:03 INFO: started backup task 'ba7c6dbb-caf2-4cd5-bca5-9a6ec98033d8'
/var/log/vzdump/qemu-103.log 2019-06-14 00:27:09 ERROR: vma_queue_write: write error - Broken pipe
/var/log/vzdump/qemu-103.log 2019-06-14 00:27:09 INFO: aborting backup job
/var/log/vzdump/qemu-103.log 2019-06-14 00:27:11 ERROR: Backup of VM 103 failed - vma_queue_write: write error - Broken pipe
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:17 INFO: Starting Backup of VM 104 (qemu)
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:17 INFO: status = running
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: update VM 104: -lock backup
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: VM Name: fischprogramme2
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: include disk 'virtio0' 'lvm-vg-pve:vm-104-disk-2' 50G
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: include disk 'virtio1' 'lvm-vg-pve:vm-104-disk-1' 2G
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: backup mode: snapshot
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: ionice priority: 7
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: creating archive '/mnt/backup_usb/dump/vzdump-qemu-104-2020_02_05-03_09_17.vma.gz'
/var/log/vzdump/qemu-104.log 2020-02-05 03:09:18 INFO: started backup task '6a3903fa-5453-42ab-a153-82320d692503'
/var/log/vzdump/qemu-104.log 2020

**Comment by edvler** [comment] 2020-05-15 03:23
The problem should be fixed with version 1.1.0.

**Closed as completed by edvler** 2020-05-15 03:23 UTC
